version: 2
updates:
  - package-ecosystem: "pip" # Still needed for GitHub Actions
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
