name: Test Documentation

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:

env:
  PYTHONVERSION: 3.8  

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v2.0.1
      with:
        python-version: ${{ env.PYTHONVERSION }}
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Cache poetry venv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ env.PYTHONVERSION }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ env.PYTHONVERSION }}-${{ hashFiles('**/poetry.lock') }}
    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install -v
    - name: Run and convert notebooks into markdown
      run: poetry run jupyter nbconvert --to markdown docs/*.ipynb
    - name: Portray - Compile as HTML
      run: poetry run portray as_html